//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bananas.Administrativo {
    
    
    public partial class CadastroCliente {
        
        /// <summary>
        /// ucToolbar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bananas.Administrativo.UserControls.ToolBar ucToolbar;
        
        /// <summary>
        /// ucCadastroCliente control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bananas.Administrativo.UserControls.InstanciaCliente ucCadastroCliente;
    }
}
